// <copyright file="PostGlobalQuickSearchConfigUpdate.cs" company="Microsoft IT">
// Copyright (c) 2012 All Rights Reserved
// </copyright>
// <author>Microsoft IT</author>
// <date>10/4/2012 5:10:35 PM</date>
// <summary>Implements the PostGlobalQuickSearchConfigUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace CRMUtil.ISV.GlobalQuickSearch_Plugin
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;

    /// <summary>
    /// PostGlobalQuickSearchConfigUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostGlobalQuickSearchConfigUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// gqs_name
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostGlobalQuickSearchConfigUpdate"/> class.
        /// </summary>
        public PostGlobalQuickSearchConfigUpdate()
            : base(typeof(PostGlobalQuickSearchConfigUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gqs_globalquicksearchconfig", new Action<LocalPluginContext>(ExecutePostGlobalQuickSearchConfigUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostGlobalQuickSearchConfigUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            if (context.Depth > 1)
            {
                return;
            }

            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            // TODO: Implement your custom Plug-in business logic.
            string _entityLogicalName = postImageEntity.GetAttributeValue<string>("gqs_name");
            base.GetAndSetFetchXml(_entityLogicalName.Trim().ToLower(), localContext.PluginExecutionContext.PrimaryEntityId, localContext.OrganizationService);
        }
    }
}
